[env:master]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = +<master_main.cpp>
upload_port = COM7
lib_deps =
    https://github.com/feilipu/Arduino_FreeRTOS_Library.git
    
[env:slave]
platform = atmelavr
board = uno
framework = arduino
upload_port = COM14
build_src_filter = +<slave_main.cpp>
lib_deps =
    https://github.com/feilipu/Arduino_FreeRTOS_Library.git

[env:UART_test_slave]
platform = atmelavr
board = uno
upload_port = COM14
framework = arduino
build_src_filter = +<UART_test_slave.cpp>

[env:UART_test_master]
platform = atmelavr
board = uno
upload_port = COM7
framework = arduino
build_src_filter = +<UART_test_master.cpp>

